[package]
name = "dio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial2 = "0.1.7"
serialport = "4.2.0"
tusk-rs = { version = "0.1.0", path = "../tusk-rs" }
