[package]
name = "silver_chariot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
num-traits = "0.2.15"
tusk = { version = "0.1.0", path = "../tusk" }
